#!/usr/bin/env python

#####################################################################################
#
# Copyright (c) 2012, Alexander Todorov <atodorov()otb.bg>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
#####################################################################################

import os
import sys
import json
import urllib
import httplib
from socket import gethostname
from exceptions import BaseException
from difio_virtualenv_python import version
from pip.util import get_installed_distributions

if os.environ.has_key('DIFIO_APP_NAME'):
    app_name = os.environ['DIFIO_APP_NAME']
else:
    app_name = os.path.basename(os.environ['VIRTUAL_ENV'])

if os.environ.has_key('DIFIO_APP_URL'):
    app_url = os.environ['DIFIO_APP_URL']
else:
    app_url = 'http://%s' % gethostname()

data = {
    'user_id'    : int(os.environ['DIFIO_USER_ID']),
    'app_name'   : app_name,
    'app_uuid'   : os.environ['DIFIO_UUID'],
    'app_type'   : 'python-%d.%d.%d' % (sys.version_info[0], sys.version_info[1], sys.version_info[2]),
    'app_url'    : app_url,
    'app_vendor' : 1000, # stand-alone virtualenv
    'pkg_type'   : 0, # Python PyPI
    'installed'  : [],
}

for dist in get_installed_distributions(local_only=True):
    data['installed'].append({'n' : dist.project_name, 'v' : dist.version})


virtualenv_version = None

try:
    from virtualenv import virtualenv_version
except ImportError, NameError:
    if os.environ.has_key('DIFIO_VIRTUALENV_VERSION'):
        virtualenv_version = os.environ['DIFIO_VIRTUALENV_VERSION']

if virtualenv_version:
    data['installed'].append({'n' : 'virtualenv', 'v' : virtualenv_version})

json_data = json.dumps(data)
params = urllib.urlencode({'json_data' : json_data})
headers = {"User-agent": "%s/%s" % (version.name, version.version)}

conn = httplib.HTTPSConnection('difio-otb.rhcloud.com')
conn.request('POST', '/application/register/', params, headers)
response = conn.getresponse()

if (response.status != 200) or (not response.getheader('Content-type').startswith('application/json')):
    raise BaseException('Communication failed - %s' % response.read())

result = json.loads(response.read())
print "Difio: %s" % result['message']
sys.exit(result['exit_code'])
